export const AVAILABLE_LLM_PROVIDERS = [
  {
    name: "On-Device",
    value: "native",
    logo: require('@/assets/llmprovider/ondevice.png'),
    description: "Install and run models on your phone.",
  },
  {
    name: "Ollama",
    value: "ollama",
    logo: require('@/assets/llmprovider/ollama.png'),
    description: "Run LLMs locally on your own machine with Ollama.",
  },
  {
    name: "LM Studio",
    value: "lmstudio",
    logo: require('@/assets/llmprovider/lmstudio.png'),
    description: "Discover, download, and run thousands of cutting edge LLMs in a few clicks.",
  },
  {
    name: "OpenAI",
    value: "openai",
    logo: require('@/assets/llmprovider/openai.png'),
    description: "Leverage OpenAI's powerful models.",
  },
  {
    name: "OpenRouter",
    value: "openrouter",
    logo: require('@/assets/llmprovider/openrouter.jpeg'),
    description: "A unified API of AI services from leading providers",
  },
  // {
  //   name: "Azure OpenAI",
  //   value: "azure",
  //   logo: require('@/assets/llmprovider/azure.png'),
  //   // options: (settings) => <AzureAiOptions settings={settings} />,
  //   description: "The enterprise option of OpenAI hosted on Azure services.",
  //   requiredConfig: ["AzureOpenAiEndpoint"],
  // },
  // {
  //   name: "Anthropic",
  //   value: "anthropic",
  //   logo: require('@/assets/llmprovider/anthropic.png'),
  //   // options: (settings) => <AnthropicAiOptions settings={settings} />,
  //   description: "A friendly AI Assistant hosted by Anthropic.",
  //   requiredConfig: ["AnthropicApiKey"],
  // },
  // {
  //   name: "Gemini",
  //   value: "gemini",
  //   logo: require('@/assets/llmprovider/gemini.png'),
  //   // options: (settings) => <GeminiLLMOptions settings={settings} />,
  //   description: "Google's largest and most capable AI model",
  //   requiredConfig: ["GeminiLLMApiKey"],
  // },
  // {
  //   name: "NVIDIA NIM",
  //   value: "nvidia-nim",
  //   logo: NvidiaNimLogo,
  //   options: (settings) => <NvidiaNimOptions settings={settings} />,
  //   description:
  //     "Run full parameter LLMs directly on your NVIDIA RTX GPU using NVIDIA NIM.",
  //   requiredConfig: ["NvidiaNimLLMBasePath"],
  // },
  // {
  //   name: "HuggingFace",
  //   value: "huggingface",
  //   logo: HuggingFaceLogo,
  //   options: (settings) => <HuggingFaceOptions settings={settings} />,
  //   description:
  //     "Access 150,000+ open-source LLMs and the world's AI community",
  //   requiredConfig: [
  //     "HuggingFaceLLMEndpoint",
  //     "HuggingFaceLLMAccessToken",
  //     "HuggingFaceLLMTokenLimit",
  //   ],
  // },
  // {
  //   name: "Local AI",
  //   value: "localai",
  //   logo: LocalAiLogo,
  //   options: (settings) => <LocalAiOptions settings={settings} />,
  //   description: "Run LLMs locally on your own machine.",
  //   requiredConfig: ["LocalAiApiKey", "LocalAiBasePath", "LocalAiTokenLimit"],
  // },
  // {
  //   name: "Novita AI",
  //   value: "novita",
  //   logo: NovitaLogo,
  //   options: (settings) => <NovitaLLMOptions settings={settings} />,
  //   description:
  //     "Reliable, Scalable, and Cost-Effective for LLMs from Novita AI",
  //   requiredConfig: ["NovitaLLMApiKey"],
  // },
  // {
  //   name: "Together AI",
  //   value: "togetherai",
  //   logo: TogetherAILogo,
  //   options: (settings) => <TogetherAiOptions settings={settings} />,
  //   description: "Run open source models from Together AI.",
  //   requiredConfig: ["TogetherAiApiKey"],
  // },
  // {
  //   name: "Fireworks AI",
  //   value: "fireworksai",
  //   logo: FireworksAILogo,
  //   options: (settings) => <FireworksAiOptions settings={settings} />,
  //   description:
  //     "The fastest and most efficient inference engine to build production-ready, compound AI systems.",
  //   requiredConfig: ["FireworksAiLLMApiKey"],
  // },
  // {
  //   name: "Mistral",
  //   value: "mistral",
  //   logo: MistralLogo,
  //   options: (settings) => <MistralOptions settings={settings} />,
  //   description: "Run open source models from Mistral AI.",
  //   requiredConfig: ["MistralApiKey"],
  // },
  // {
  //   name: "Perplexity AI",
  //   value: "perplexity",
  //   logo: PerplexityLogo,
  //   options: (settings) => <PerplexityOptions settings={settings} />,
  //   description:
  //     "Run powerful and internet-connected models hosted by Perplexity AI.",
  //   requiredConfig: ["PerplexityApiKey"],
  // },
  // {
  //   name: "OpenRouter",
  //   value: "openrouter",
  //   logo: OpenRouterLogo,
  //   options: (settings) => <OpenRouterOptions settings={settings} />,
  //   description: "A unified interface for LLMs.",
  //   requiredConfig: ["OpenRouterApiKey"],
  // },
  // {
  //   name: "Groq",
  //   value: "groq",
  //   logo: GroqLogo,
  //   options: (settings) => <GroqAiOptions settings={settings} />,
  //   description:
  //     "The fastest LLM inferencing available for real-time AI applications.",
  //   requiredConfig: ["GroqApiKey"],
  // },
  // {
  //   name: "KoboldCPP",
  //   value: "koboldcpp",
  //   logo: KoboldCPPLogo,
  //   options: (settings) => <KoboldCPPOptions settings={settings} />,
  //   description: "Run local LLMs using koboldcpp.",
  //   requiredConfig: [
  //     "KoboldCPPModelPref",
  //     "KoboldCPPBasePath",
  //     "KoboldCPPTokenLimit",
  //   ],
  // },
  // {
  //   name: "Oobabooga Web UI",
  //   value: "textgenwebui",
  //   logo: TextGenWebUILogo,
  //   options: (settings) => <TextGenWebUIOptions settings={settings} />,
  //   description: "Run local LLMs using Oobabooga's Text Generation Web UI.",
  //   requiredConfig: ["TextGenWebUIBasePath", "TextGenWebUITokenLimit"],
  // },
  // {
  //   name: "Cohere",
  //   value: "cohere",
  //   logo: CohereLogo,
  //   options: (settings) => <CohereAiOptions settings={settings} />,
  //   description: "Run Cohere's powerful Command models.",
  //   requiredConfig: ["CohereApiKey"],
  // },
  // {
  //   name: "LiteLLM",
  //   value: "litellm",
  //   logo: LiteLLMLogo,
  //   options: (settings) => <LiteLLMOptions settings={settings} />,
  //   description: "Run LiteLLM's OpenAI compatible proxy for various LLMs.",
  //   requiredConfig: ["LiteLLMBasePath"],
  // },
  // {
  //   name: "DeepSeek",
  //   value: "deepseek",
  //   logo: DeepSeekLogo,
  //   options: (settings) => <DeepSeekOptions settings={settings} />,
  //   description: "Run DeepSeek's powerful LLMs.",
  //   requiredConfig: ["DeepSeekApiKey"],
  // },
  // {
  //   name: "PPIO",
  //   value: "ppio",
  //   logo: PPIOLogo,
  //   options: (settings) => <PPIOLLMOptions settings={settings} />,
  //   description:
  //     "Run stable and cost-efficient open-source LLM APIs, such as DeepSeek, Llama, Qwen etc.",
  //   requiredConfig: ["PPIOApiKey"],
  // },
  // {
  //   name: "AWS Bedrock",
  //   value: "bedrock",
  //   logo: AWSBedrockLogo,
  //   options: (settings) => <AWSBedrockLLMOptions settings={settings} />,
  //   description: "Run powerful foundation models privately with AWS Bedrock.",
  //   requiredConfig: [
  //     "AwsBedrockLLMAccessKeyId",
  //     "AwsBedrockLLMAccessKey",
  //     "AwsBedrockLLMRegion",
  //     "AwsBedrockLLMModel",
  //   ],
  // },
  // {
  //   name: "APIpie",
  //   value: "apipie",
  //   logo: APIPieLogo,
  //   options: (settings) => <ApiPieLLMOptions settings={settings} />,
  //   description: "A unified API of AI services from leading providers",
  //   requiredConfig: ["ApipieLLMApiKey", "ApipieLLMModelPref"],
  // },
  {
    name: "Generic OpenAI",
    value: "generic-openai",
    logo: require('@/assets/llmprovider/generic-openai.png'),
    description:
      "Connect to any OpenAi-compatible service via a custom configuration",
  },
  // {
  //   name: "xAI",
  //   value: "xai",
  //   logo: XAILogo,
  //   options: (settings) => <XAILLMOptions settings={settings} />,
  //   description: "Run xAI's powerful LLMs like Grok-2 and more.",
  //   requiredConfig: ["XAIApiKey", "XAIModelPref"],
  // },
];